---
baseURL: https://blog.de-souza.eu
languageCode: en-us
title: Léo's Blog
metaDataFormat: yaml
rssLimit: 10
copyright: 'Copyright © 2019 Léo De Souza - Except where otherwise noted, content
  on this site is licensed under a Creative Commons Attribution 4.0 International
  License (http://creativecommons.org/licenses/by/4.0/).

'
params:
  footer: 'Copyright © 2019 Léo De Souza - Except where otherwise noted, content on
    this site is licensed under a <a href="http://creativecommons.org/licenses/by/4.0/"
    rel="license"> Creative Commons Attribution 4.0 International License</a>.

'
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
taxonomies:
  tag: tags
menu:
  main:
  - name: RSS
    url: /index.xml
    weight: 4
